#!/bin/sh

# script/ci-bootstrap - make sure all required dependencies are setup

# exit on sub-module failure
set -e

# move to parent dir
cd "$(dirname "$0")/.."

# ------

echo "Bootstrapping.."
date "+%H:%M:%S"
echo ""

echo "--------- "

# install brew cask
brew install caskroom/cask/brew-cask

# install xamarin components
brew cask install xamarin xamarin-jdk xamarin-ios xamarin-studio

echo "--------- "

echo "local apps"
ls -la ~/Applications

echo "root apps"
ls -la /Applications
